// ** Graphql
import pkg from "graphql";
const {
  GraphQLList,
  GraphQLObjectType,
  GraphQLString,
  GraphQLInt,
  GraphQLBoolean,
  GraphQLFloat,
} = pkg;

const homepageType = new GraphQLObjectType({
  name: "homepageType",
  fields: () => ({
    _id: { type: GraphQLString },
    heroType: { type: GraphQLString },
    heroImagesLarge: { type: new GraphQLList(GraphQLString) },
    heroImagesSmall: { type: new GraphQLList(GraphQLString) },
    heroHeading: { type: GraphQLString },
    heroSubHeading: { type: GraphQLString },
    heroBtnText: { type: GraphQLString },
    heroLink: { type: GraphQLString },
    heroCountdown: { type: GraphQLFloat },
    heroCountdownText: { type: GraphQLString },
    marquee: { type: GraphQLBoolean },
    marqueeText: { type: GraphQLString },
    subHeroTitle: { type: GraphQLString },
    subHeroImages: { type: new GraphQLList(GraphQLString) },
    subHeroHeading: { type: new GraphQLList(GraphQLString) },
    subHeroBtnText: { type: new GraphQLList(GraphQLString) },
    subHeroLink: { type: new GraphQLList(GraphQLString) },
    riskReducersImages: { type: new GraphQLList(GraphQLString) },
    riskReducersHeading: { type: new GraphQLList(GraphQLString) },
    riskReducersText: { type: new GraphQLList(GraphQLString) },
    spotlight1: { type: GraphQLBoolean },
    spotlight1Image: { type: GraphQLString },
    spotlight1Link: { type: GraphQLString },
    spotlight2: { type: GraphQLBoolean },
    spotlight2Image: { type: GraphQLString },
    spotlight2Link: { type: GraphQLString },
    categoryTitle: { type: GraphQLString },
    categoryImages: { type: new GraphQLList(GraphQLString) },
    categoryHeading: { type: new GraphQLList(GraphQLString) },
    categoryText: { type: new GraphQLList(GraphQLString) },
    categoryLink: { type: new GraphQLList(GraphQLString) },
    newsletter: { type: GraphQLBoolean },
    newsletterHeading: { type: GraphQLString },
    newsletterText: { type: GraphQLString },
    newsletterBtnText: { type: GraphQLString },
    newsletterSuccessHeading: { type: GraphQLString },
    newsletterSuccessText: { type: GraphQLString },
    trending: { type: GraphQLBoolean },
    trendingLimit: { type: GraphQLInt },
    status: { type: GraphQLInt },
    message: { type: GraphQLString },
  }),
});

export default homepageType;
